apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-express
  name: simple-express-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/simple-express-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: simple-express
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
